=== raml-apis/Postmark/schemas/mail-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "From" : {
      "type" : "string" ,
      "required" : false
    } ,
    "To" : {
      "type" : "string" ,
      "required" : false
    } ,
    "Cc" : {
      "type" : "string" ,
      "required" : false
    } ,
    "Bcc" : {
      "type" : "string" ,
      "required" : false
    } ,
    "Subject" : {
      "type" : "string" ,
      "required" : false
    } ,
    "Tag" : {
      "type" : "string" ,
      "required" : false
    } ,
    "HtmlBody" : {
      "type" : "string" ,
      "required" : false
    } ,
    "TextBody" : {
      "type" : "string" ,
      "required" : false
    } ,
    "ReplyTo" : {
      "type" : "string" ,
      "required" : false
    } ,
    "Headers" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "Name" : {
              "type" : "string" ,
              "required" : false
            } ,
            "Value" : {
              "type" : "string" ,
              "required" : false
            }
          }
        }
      ]
    } ,
    "Attachments" : {
      "type" : "array" ,
      "required" : false ,
      "items" : {
        "type" : "object" ,
        "properties" : {
          "Name" : {
            "type" : "string" ,
            "required" : false
          } ,
          "Content" : {
            "type" : "string" ,
            "required" : false
          } ,
          "ContentType" : {
            "type" : "string" ,
            "required" : false
          } ,
          "ContentID" : {
            "type" : "string" ,
            "required" : false
          }
        }
      }
    }
  }
}

=== raml-apis/Postmark/examples/emails-example.json
[
  {
    "From" : "sender@example.com" ,
    "To" : "receiver@example.com" ,
    "Cc" : "copied@example.com" ,
    "Bcc" : "blank-copied@example.com" ,
    "Subject" : "Test" ,
    "Tag" : "Invitation" ,
    "HtmlBody" : "<b>Hello</b>" ,
    "TextBody" : "Hello" ,
    "ReplyTo" : "reply@example.com" ,
    "Headers" : [
      {
        "Name" : "CUSTOM-HEADER" ,
        "Value" : "value"
      }
    ] ,
    "Attachments" : [
      {
        "Name" : "readme.txt" ,
        "Content" : "dGVzdCBjb250ZW50" ,
        "ContentType" : "text/plain"
      } , {
        "Name" : "report.pdf" ,
        "Content" : "dGVzdCBjb250ZW50" ,
        "ContentType" : "application/octet-stream"
      } , {
        "Name" : "bacon.jpg" ,
        "Content" : "/9j/4AAQSkZJRgABAgEAAAAAAAD/4" ,
        "ContentType" : "image/jpeg" ,
        "ContentID" : "cid:part1.01030607.06070005@gmail.com"
      }
    ]
  }
]
